[package]
name = "cargo_advanced"
version = "0.1.0"
edition = "2021"

# These are the default values for opt-level
[profile.dev]
opt-level = 0
[profile.release]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
